### ISSUE TITLE
ADDING JSON FILE @ RUNTIME FROM API

### ISSUE THREAD

**Issue by harishmaddula32** [Baglan/MCLocalization#14]
Hi Baglan,

I'm creating a JSON file and saving it in document directory when application is launching in , After that i'm referring to that path to read JSON file. But unfortunately application is crashing

    NSArray *keys = [NSArray arrayWithObjects:@"greeting",@"message",@"glory",@"mustache",@"lovely-mustache",nil];
    NSArray *values = [NSArray arrayWithObjects:@"గ్రీటింగ్",@"సందేశం",@"గ్లోరీ",@"మీసం",@"సుందరమైన మీసం",nil];
    NSDictionary * dic = [NSDictionary dictionaryWithObjects:values forKeys:keys];
    
    NSError *error;
    NSData* jsonData = [NSJSONSerialization dataWithJSONObject:dic options:NSJSONWritingPrettyPrinted error:&error];
    NSString *jsonStr = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    
    [self writeStringToFile:jsonStr :@"sp.json"];

- (void)writeStringToFile:(NSString*)aString :(NSString*)fileNameStr{
    // Build the path, and create if needed.
    fileName = fileNameStr;
    NSString* filePath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
    fileAtPath = [filePath stringByAppendingPathComponent:fileName];
    
    if (![[NSFileManager defaultManager] fileExistsAtPath:fileAtPath]) {
        [[NSFileManager defaultManager] createFileAtPath:fileAtPath contents:nil attributes:nil];
    }
    
    // The main act...
    [[aString dataUsingEncoding:NSUTF8StringEncoding] writeToFile:fileAtPath atomically:NO];
}

// Using a file path:
    [MCLocalization loadFromJSONFile:fileAtPath defaultLanguage:@"sp"];

`CRASHING`
 SOME WHERE 
[__NSCFString objectForKeyedSubscript:]
![screen shot - 1](https://user-images.githubusercontent.com/3964198/34983188-bbd848a8-fad2-11e7-9662-f572bfb3a520.png)
![screen shot - 2](https://user-images.githubusercontent.com/3964198/34983189-bc1ca7be-fad2-11e7-9d2f-eb4f31b06bbc.png)

**Comment by Baglan** [comment]
It would appear that you are using the ***[MCLocalization loadFromJSONFile:defaultLanguage:]*** method that assumes that you have a different data structure in your JSON file. You should either change your file to contain all localization languages with a structure like this:

```json
{
  "en": {
    "greeting": "Hello!",
    "message": "Tap on the buttons below to switch languages",
    "glory": "Glory Glory, %name%!",
    "mustache": "mustache",
    "lovely-mustache": "What a wonderful {{mustache}} you have!"
  },
  "ru": {
    "greeting": "Привет!",
    "message": "Нажимайте на кнопки для смены языка",
    "glory": "Славься славься, %name%!",
    "mustache": "усы",
    "lovely-mustache": "Какие замечательные у Вас {{mustache}}!"
  }
}
```

Alternatively, you can use separate files with the structure that you already use, e.g.:

```json
{
  "greeting": "Hello!",
  "message": "Tap on the buttons below to switch languages",
  "glory": "Glory Glory, %name%!",
  "mustache": "mustache",
  "lovely-mustache": "What a wonderful {{mustache}} you have!"
}
```

In that case you should load them using this method:

```objective-c	
NSDictionary * languageURLPairs = @{
    @"en":[[NSBundle mainBundle] URLForResource:@"en.json" withExtension:nil],
    @"ru":[[NSBundle mainBundle] URLForResource:@"ru.json" withExtension:nil],
};
[MCLocalization loadFromLanguageURLPairs:languageURLPairs defaultLanguage:@"en"];
```

**Comment by harishmaddula32** [comment]
Thank's for reply, 

Initially i'm loading in english language with en.json file locally it's working fine. But when i'm hitting API and storing response as a file in DOCUMENT DIRECTORY as sp.json file. After storing in document directory i'm clicking on a button to change language, i'm writing piece of code for changing language 

 NSDictionary * languageURLPairs = @{ @"sp":fileAtPath};
 [MCLocalization loadFromLanguageURLPairs:languageURLPairs defaultLanguage:@"sp"];

I'm using same JSON format for single language single file 

LOG
2018-01-17 11:02:57.819 Localize_Language[1516:144450] MCLocalization: no string for key glory in language en
2018-01-17 11:02:57.820 Localize_Language[1516:144450] MCLocalization: no string for key message in language en

I printed the JSON file content and it is having data in correct format. Can u help me from this where i'm doing wrong 

![1](https://user-images.githubusercontent.com/3964198/35027576-7cb6de46-fb77-11e7-9998-12797e418972.png)
![2](https://user-images.githubusercontent.com/3964198/35027577-7ce32b5e-fb77-11e7-8616-0fb0334aa4fd.png)
![3](https://user-images.githubusercontent.com/3964198/35027578-7d0eec94-fb77-11e7-9475-7279f9ccef27.png)

**Comment by Baglan** [comment]
Those methods require URLs. You already have the file path and you can convert it to URL using

***+[NSURL fileURLWithPath:]***

**Comment by harishmaddula32** [comment]
As per your suggestion i changed a piece of code in button action 

- (IBAction)changeLang:(id)sender {
    NSDictionary * languageURLPairs = @{@"sp":[NSURL fileURLWithPath:fileAtPath]};
    [MCLocalization loadFromLanguageURLPairs:languageURLPairs defaultLanguage:@"sp"];
}

After trying this method it's working fine as smooth. Thanks for your support Baglan

**Comment by Baglan** [comment]
Great! The documentation for the library could definitely be better :)
