### ISSUE TITLE
noKeyPlaceholder

### ISSUE THREAD

**Issue by magnett** [Baglan/MCLocalization#9]
Hi and thanks for your time.
I am probably missing something...is there a way to replace a missing translation with the same key from the one set as default?

**Comment by Baglan** [comment]
Hi,

The purpose of the "noKeyPlaceholder" was to provide placeholder text in case actual localization is not yet available.

There is no direct way to "fall through" to some default localization, however, in case the "noKeyPlaceholder" is not set, you can do something like:

	NSString * key = @"my-key";
	NSString * defaultLanguage = @"en";

	NSString * localizedString = [MCLocalization stringForKey:key];
	if (!localizedString) {
		MCLocalization * localization = [MCLocalization sharedInstance];
		localizedString = [localization stringForKey:key language:defaultLanguage]
	}

Quite verbose even if it could be reduced to a one-liner.

Placeholder text was a solution for a very narrow problem and "fall-through" defaults is a good idea, perhaps there could be a delegate call to handle the situation when key is not found. I'll think about it.

**Comment by Baglan** [comment]
I'm closing this issue as there wasn't any activity associated with it for more than 4 years :).
